[package]
name = "solana-fellowship-assignment"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = "3.1.11"
serde = {version="1.0.219", features=["derive"]}
solana-sdk = "2.3.1"
tokio = {version="1.45.1", features=["full"]}
